name: ar_furniture_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  searchable_listview:  2.10.0
  babylonjs_viewer: ^1.0.1
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.7.0
  concentric_transition: ^1.0.3
  csv: ^5.1.1
  animations: ^2.0.11
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_ui_auth: ^1.12.1
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.2.17
  provider: ^6.1.1
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/models/
  - assets/products/
  - assets/